<?php

/**
 * @file
 * Provides basic functionality and customization for ps267.org.
 *
 * When enabled this module makes small improvements to the editorial
 * experience and functionality of the site.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_form_FORM_ID_alter() for the node-resource-page-form form.
 */
function ps267_form_node_resource_page_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $children_keys = Element::children($form['field_resource_icon']['widget']);
  foreach ($children_keys as $key) {
    $form['field_resource_icon']['widget'][$key]['icon_name']['#field_prefix'] = '';
    $form['field_resource_icon']['widget'][$key]['icon_name']['#title'] = $form['field_resource_icon']['widget'][$key]['#title'];
    // @see https://www.drupal.org/project/fontawesome/issues/2967906
    // $form['field_resource_icon']['widget'][$key]['settings']['#access'] = FALSE;
  }

}

/**
 * Implements hook_form_FORM_ID_alter() for the user-register-form form.
 */
function ps267_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['entity_options']['#access'] = FALSE;
}

/**
 * Implements hook_widget_WIDGET_TYPE_alter.
 *
 * @see https://www.drupal.org/project/paragraphs/issues/2868155#comment-12566372
 */
function ps267_field_widget_entity_reference_paragraphs_form_alter(&$element, &$form_state, $context){
  if ($element['#paragraph_type'] == "text_with_image") {
    $element['subform']['field_text_with_image_button']['widget'][0]['title']['#title'] = t('Button text');
  }
}

/**
 * Implements hook_ds_pre_render_alter.
 */
function ps267_ds_pre_render_alter(&$layout_render_array, $context, &$vars) {
  // For event teasers, only show the title if no image exists.
  if ($context['entity_type'] == 'node' && $context['bundle'] == 'event' && $context['view_mode'] == 'teaser') {
    if ($context['entity']->get('field_event_image')->isEmpty()) {
      $layout_render_array['ds_content']['field_event_image']['#access'] == FALSE;
    }
    else {
      $layout_render_array['ds_content']['node_title']['#access'] = FALSE;
    }
  }
}