# Schema for field settings related to Custom Add Another module.

field.field.*.*.*.third_party.custom_add_another:
  type: mapping
  label: 'Custom Add Another field settings'
  mapping:
    custom_add_another:
      type: string
      label: 'Custom "Add another item" button text'
    custom_remove:
      type: string
      label: 'Custom "Remove" button text'
