# Schema for the configuration files of the footer message module.
footer_message.settings:
  type: config_object
  label: 'Footer message settings.'
  mapping:
    footer_message_msg:
      type: string
      label: 'Footer message text.'
    footer_message_format:
      type: string
      label: 'Footer message text format.'
