<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function eses_preprocess_block__system_branding_block(&$variables) {
  if($variables['content']['site_name']['#access']) {
    $variables['site_name'] = "East Side Elementary School";
  }
}

function eses_preprocess_region__sidebar_first(&$variables) {
  $variables['#attached']['library'] = "eses/eses";
}