<?php


/**
 * @file
 * Contains Contact Form D8 module.
 */

/**
 * Implements hook_mail_alter().
 */
function contact_categories_mail_alter(&$message) {
    // Check that the message isn't a copy sent to the sender (page_copy).
    if (($message['key'] == 'page_mail') && isset($message['params']['contact_message'])) {
        $contact_message = $message['params']['contact_message'];
        foreach ($contact_message->getFields() as $field) {
            if ($field->getName() === 'field_categories' ) {
                // Add the category's recipient to the message.
                foreach ($field as $delta => $item) {
                    $email = contact_categories_strip_comment($item->value);
                    $message['to'] .= ',' . $email;
                }
            }
        }
    }
}

/**
 * Strips the "comment" from an email address.
 *
 * According to the spec, email addresses can have a comment string inside
 * parenthesis before or after the main part of the address (the string before
 * the '@'). Remove that comment since this module uses it to allow multiple
 * categories to send to the same address. E.g. jane(1)@gmail.com and
 * jane(2)@gmail.com should both ultimately send to jane@gmail.com. Note: we can
 * assume that there will be no nested parentheses since that violates the spec
 * and our general use-case.
 *
 * @param string $email
 *
 * @return string
 */
function contact_categories_strip_comment($email) {
  return preg_replace('/\(.*\)/', '', $email);
}