default_button: true
default_message: true
default_tab: false
default_tab_edit: false
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  announcement: true
  calendar_event: true
  fundraiser: true
  page: true
  resource_page: true
message:
  announcement: true
  calendar_event: true
  fundraiser: true
  page: true
  resource_page: true
tab:
  announcement: false
  calendar_event: false
  fundraiser: false
  page: false
  resource_page: false
tab_edit:
  announcement: false
  calendar_event: false
  fundraiser: false
  page: false
  resource_page: false
