module:
  addanother: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  button_link: 0
  ckeditor: 0
  config: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  custom_add_another: 0
  datetime: 0
  dblog: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  footer_message: 0
  google_map_field: 0
  gtranslate: 0
  help: 0
  hide_revision_field: 0
  image: 0
  layout_discovery: 0
  link: 0
  media: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  ps267: 0
  quickedit: 0
  rdf: 0
  scheduler: 0
  search: 0
  shortcut: 0
  site_alert: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_fieldsets: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  bootstrap: 0
  eses: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
