cdn_provider: ''
logo:
  path: themes/custom/eses/images/eses_logo.png
  url: ''
  use_default: false
_core:
  default_config_hash: 2gj5VADHA5qZ7eCPDBzaY3sRIiA4d4uD4cfl5z7Yfv8
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://ps267.docker.localhost:8002/themes/custom/eses/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  eses: 8000
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
  node_user_picture: false
navbar_position: fixed-top
table_responsive: '-1'
table: ''
